# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  # Tell Netlify Dev which port your Vite server runs on
  targetPort = 5174
  port = 8888
  publish = "dist"
  functions = "netlify/functions"

[dev.environment]
  VITE_API_URL = "https://controle-animal.onrender.com"
  VITE_API_KEY = "senhaanimal"