[dev]
  framework = "vite"
  targetPort = 5174

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "https://controle-animal-production.up.railway.app/:splat"
  status = 200
  force = true
